### ISSUE TITLE
Centrifuge has suction when there is processed essence

### ISSUE THREAD

**Issue by janinko** [Azanor/thaumcraft-5#138]
Centrifuge has suction of 128, when there is no essence being processed. However as long as there is already processed essence, centrifuge won't accept new essence for processing.

Centrifuge should not have suction, when it won't accept new essence i.e. centrifuge should not have suction, when there is processed essence in it.

Thaumcraft version: 5.0.3

**Comment by Azanor** [comment]
This will really slow down its operation. Why exactly is it a problem anyway?

**Comment by janinko** [comment]
I have a setup, where when centrifuge output is clogged, its suction overpower suction from a jar where the clogging essence could flow otherwise.

When there is essence being processed, the centrifuge has suction 64. Maybe if it will have suction 64 also when there is processed essence in centrifuge it will help? (My scenario could deal with suction 64, I don't know if it will still slow centrifuge operation.)

Or maybe if there would be some delay, let's say after 20 ticks, if there is still essence on the output, lower the suction. But this would be harder to implement and will also slow the unclogging.

**Comment by ThePB** [comment]
i do not have a screenshot or anything, but it is possible that your system just needs a restricted tube to be added. (sorry for the plug, i know this is not the place for discussions)

**Comment by MalkContent** [comment]
Janinko, I'm pretty sure you just set that up wrongly. Input into centrifuge is bottom, output is top; don't connect the two.
The centrifuge is pulling at half suction when working because (I think) this allows it to still draw from jars and keep the tubes leading up to the centrifuge filled, so the essentia flow doesn't change direction all the time. Also it halves so neighboring centrifuges that are NOT working yet, can overpower the suction of the working one, and get working, too. (I think)
Post a screenshot so we (by which I mean Azanor) can see if you just done goofed or if you encountered a bug.

**Comment by janinko** [comment]
Here is simplified picture of my setup. Actual setup is bigger (contains jars for all kinds of essence) and bit more complicated, but that's not issue.
![centrifuge-setup](https://cloud.githubusercontent.com/assets/644267/11715721/4cfce2ae-9f44-11e5-8015-b58ed7ec481d.png)

How it works:
 * In smelter, essence is smelted and goes into buffer *S*
 * From buffer *S* the essence is sucked to buffer *L1* in to the buffer loop
   * If the essence in buffer *L1* is the same as the filtering tube, it is sucked into *J1* (typed suction 31)
   * If the essence in buffer *L1* is different then the filtering tube, it is sucked into buffer *L2* (untyped suction 1)
   * The same apply for buffers *L1* through *L5*
 * From buffer *L6* the essence is sucked into:
   * Jar *J6* if the essence is the right type and *J6* is not full (typed suction 31)
   * Jar *J7* if the essence is the right type and *J6* is full (typed suction 30)
   * Buffer *L7* otherwise
 * From buffer *L7* the essence is sucked into *L8* and so on until *L12*
 * From *L12* the essence is sucked back into *L1*
   * This loop is there for the case when a jar is full, the essence will go round the loop, until the jar is emptied.
   * If the loop is full, it can get stuck and will not accept essence from *S*, but after the appropriate jar is emptied, it continues to work.

How it works with centrifuge:
 * When centrifuge is empty
   * It has suction 128
   * The restricted tube *R* drops down the suction to (for example) 40
   * Suction 40 is bigger then 32, so essence is sucked from jar *J7* or *J6* into centrifuge
 * When centrifuge is working
   * It has suction 64
   * The restricted tube *R* drops down the suction below 32
     * This can cause essentia go back from tubes into jars or some venting, slowing the process in result. I don't care about slow process.
 * When centrifuge stops working
   * There is essence in the centrifuge output. When everything is OK, it is sucked into buffer *C*
   * The centrifuge suction goes back to 128 (even when the essence in output is still there)

What is wrong:
 * When the loop gets stucked because some reason for a while, there can accumulate essence that would normally go to jar *J6* or *J7*
 * If loop is stucked, buffers *S* and *C* will eventually be filled to maximum
 * If buffer *C* is filled, the essence from centrifuge output will not go out
 * If there is essence in the centrifuge output, the centrifuge will not accept new essence to processing, but still has suction 128
 * Because there is bigger suction then 32 in the tubes above jars *J7* and *J6* (in example 39, 38 after the restricted tube), the essence will not go into the jars
 * In effect, there is essence in the loop, that could flow into jars *J6* or *J7* and unstuck the loop, but it wont.

If the centrifuge had suction 64 also when there is essence in it's output, there wouldn't be suction overpowering suction from jars *J7* and *J6* and the essence could flow into them.


I agree that dropping the suction to 0 would slow centrifuge processing. I think keeping it at 64 until the essence from output is sucked out of centrifuge will not slow centrifuge, because the essence is not sucked into centrifuge when there is some in the output.

**Comment by MalkContent** [comment]
If the suction isn't higher than the jars at any given point, the jar will suck it back. ThePB is right, this is what restriction tubes are for. And there's other ways to solve this, too.

**Comment by janinko** [comment]
@MalkContent I'm using restriction tubes, but restriction tubes just halve suction coming from somewhere else. Now the suction from centrifuge is lower that from jars, when the centrifuge is processing an essence. I've wrote it here:
> * When centrifuge is working

_____

A centrifuge works in these 3 states:

| Essence IN | Essence OUT | Processing | Accepting essence | Suction |
|:----------:|:-----------:|:----------:|:-----------------:|:-------:|
|    None    |     None    |    False   |        True       |   128   |
|    Some    |     None    |    True    |       False       |    64   |
|    None    |     Some    |    False   |       False       |   128   |

Using restriction tube, I can modify the suction to eg. 56 and 24. So at some time, suction is grater then from jar and at some time suction is lower.
But the problem is there is possibility that centrifuge will have high suction and will not accept essence.

**Comment by ThePB** [comment]
I think the change could be good, but that's Azanor's call. In my opinion, it's more fun trying to work around some of this peculiar problems with other solutions... see below.

For your problem:

Remember that buffers/jars are comparator - able. You can check fullenss on the "C" buffer and send the redstone signal to the centrifuge, setting suction to 0 automaticallly or, if you prefer, send it to a valve, keeping suction on the part of the tube system that's not cut off and so keeping a little buffer of essentia ready.

If i may add:

If i understand what you are trying to do correctly j6 and 7 are buffers for the centrifuge that are there to be filled on the down times while also clearing the loop of a particular essentia if the system gets stuck.  I'm not really a fan of this type of systems. If i know some aspect is going to cause problems, i'll handle it in a separate system. Not as easy to do now without golems, but that's just my idea.

Even with the addition of flux, you should think about adding a primalizer (and void jars for primal aspects) for cleaning the pipes in case of clogging in an automated fashion. It causes flux, but it should not be that much of a problem since you already have such a system set up.

I would prefer having a system with the C buffer between the S and the L1, giving priority to the "in loop" essentia to the "freshly added" one. It should help clearing clogged system faster.

i do not understand why you are having j6 and j7 both with filtered tubes. Or, to be frank, why using filtered essentia tubes in this system at all instead of labels. Even in your system as is, it would have been better for all the jars to be labelled direclty. Less costly, too, as only one filtered tube would have been needed for the centrifuge. This should help with speed, too.

Anyway, again, this is not the place for discussion about this, if you have a minecraftforums account, my profile name is TPB, feel free to pm me if you want
