### ISSUE TITLE
Thaumometer questionmarks reappear after relog

### ISSUE THREAD

**Issue by BerciTheBeast** [Azanor/thaumcraft-5#196]
I started a new server, made myself some stuff, including a thaumometer. I went about scanning things. Once I relogged, I noticed that question marks appeared on things I am 100% certain I scanned. When I tried to rescan, it said I was unable to learn anything.

Modlist:
-Minecraft Coder Pack 9.18
-Forge Mod Loader 8.0.99.99
-Minecraft Forge 11.15.0.1692
-Blood Magic: Alchemical Wizardry 1.8.9-2.0.0-1
-Baubles 1.1.3.0
-Thaumcraft 5.1.1
-Botania r1.8-249
-Inventory Tweaks 1.60-dev-27-43ecdd2
-Just Enough Items 2.15.1.71
-Just Enough Items Addons 0.7.1.28
-JourneyMap 1.8.8-5.1.3
-Waila 1.6.0-B3
-What Are We Looking At 1.4.1

**Comment by BerciTheBeast** [comment]
Issue disappeard after some more relogging and removing botania and blood magic.

**Comment by errecepe** [comment]
I think this and https://github.com/Azanor/thaumcraft-5/issues/130 were the same.

It's happened to me with only thaumcraft mod. Researches and scanned objects are not sync until you open at least 2 times thaumonomicom. Until you open at least 2 times, all the previous scanned objects appears like not scanned (with question marks, but u CANT scan it again)

It was happening to me, playing on a server. 
Not tried on single player.

I think is fixed (at least to me) since 5.1.x
