### ISSUE TITLE
(1.8.9) (Thaumcraft 5.1.4) Glowstone dust prefers to be duplicated over making Nitor

### ISSUE THREAD

**Issue by DarcClan** [Azanor/thaumcraft-5#314]
Having both Nitor and Alchemical Duplication Researched, if you fill a crucible (with boiling water) with 2 candles and 1 charcoal (which gives you a total of 2 ignis 2 lux 2 potentia & 2 victus) and then throw in 2 glowstone dust at the same time you get 2 glowstone back (one breaks down and the other gets duplicated). This was tested in both server and singleplayer enviorment. Should the Glowstone related duplication maybe be set to glowstone blocks as to not interfere with nitor creation? (of course with a higher required Lux and Sensus requirments to match)

**Comment by Xirema** [comment]
This is one of the disadvantages of using raw Crucibles. You'll want to move up to a Thaumatorium, which won't make these kinds of mistakes.

**Comment by ThePB** [comment]
Or prehaps it would be better to double check your recipe on the thaumonomicon before trying to create something :D
You are sorely lacking aspects in that crucible. I have no idea how 2 victus got in, but for nitor you need 3 of potentia, ignis and lux. That's why it does not work :D

Now, the "bug" might still be there if you use a glowstone BEFORE having enough lux, but i've not tried :D

**Comment by DarcClan** [comment]
OK, yea it seems that my font turned the 3's into what looked like 1's. I assumed that the ammount needed was just 1 of each now. nevermind....
