### ISSUE TITLE
Feature Request: Golem Control Seal: restock

### ISSUE THREAD

**Issue by Xiaminou** [Azanor/thaumcraft-5#322]
Add a golem seal to restock a given inventory.
Right now restocking an inventory requires 2 Store and 1 Empty seals and golems will always try to empty the storage inventory creating a loop which is less than optimal.
It works, and with priority you can have a golem doing other tasks too, but I'd still like to see a seal for that specific task.

here is a video example of current golem behavior:
https://www.youtube.com/watch?v=KbSafBXKSs0&feature=youtu.be

**Comment by runfalk** [comment]
Couldn't a store seal with provisioning support provide this functionality?

**Comment by MalkContent** [comment]
I wonder what the use of an empty seal would be, if store could make use of provisioning, too.

**Comment by Xiaminou** [comment]
store does not request items, it only says "hey you can store this here". Because the golems don't know when the "store" inventory is full or not and therefore they'll keep trying and it gets them stuck, the video is pretty self explanatory to be honest.
I'm not sure what you mean by "store with provisioning support", but unless it actively requests items when the stock is not complete, it wouldn't do.

**Comment by MalkContent** [comment]
That's exactly what provisioning would do for store. What else would there be.
So long as the inventory of the block store is placed against isn't full, it'd look at nearby provision seals' inventories to restock from.

Anyways, you can control restocking with redstone for now. If all containers you want to be restocked, are restocked, disable the empty seal with redstone. If you have containers with mixed items, you'll likely need computercraft or opencomputers to detect the restocking being fulfilled, though. Otherwise comparators will do the trick.

**Comment by Xiaminou** [comment]
which makes it pretty hard and needing alot of space, provisioning would be much easier.

**Comment by Azanor** [comment]
Since you can now specify how much of an item you want the store seal to place in an inventory I think this is pretty much handled. You are free to try and convince me otherwise :)

**Comment by MalkContent** [comment]
If I'm not wrong, quantity wasn't the issue here.
The issue is that you can not softly move items from one container to another.
You need to place an empty seal on container a and a store seal on container b. But the golem will /always/ empty container a, no matter if there is a store seal that wants it or not.

**Comment by Xiaminou** [comment]
Malk is right, right now you need 3 seals to restock an inventory.
1. Empty (for the feeding container)
2. Store (on the feeding container so the golem can return items if the restocked container is full)
3. Store (on the restocked container)

But the golem will always try to Empty the feeding container. What I (we) am (are) proposing is:
1. Provide (for the feeding container)
2. Store (on the restocked container)
so the Store seal can go pick-up from the provide container.
