### ISSUE TITLE
Screen goes black when warp effect unnatural hunger strikes.

### ISSUE THREAD

**Issue by MineCharls** [Azanor/thaumcraft-5#378]
That's it. It even remains black in the pause menu. I'm using Thaumcraft 5.1.6 and latest version of forge and optifine. I' don't know if it's caused by forge or optifine. I think other warp effects may have the same result but sometimes it's difficult to se which one strikes as the screen goes black.

**Comment by MalkContent** [comment]
see here https://github.com/Azanor/thaumcraft-5/issues/375

**Comment by Reykja** [comment]
I have had several times when the screen goes black during various events. Every time, it has been a setting in Optifine that was conflicting with TC. The problem was solved by adjusting Optifine settings. I can never remember which one it is that I adjust, but I think it's either the Fog setting or the Fast Render setting. I currently have Fog set to Fast and the Fast Render set to Off.

**Comment by MineCharls** [comment]
Thank you very much. I will try.

**Comment by Majestyc2k1** [comment]
Its fast Render. I posted this same question to Optifine.
