### ISSUE TITLE
Alchemy Recipe: Sand

### ISSUE THREAD

**Issue by ReTeYeZ** [Azanor/thaumcraft-5#453]
Imo one of the most important alchemy recipes, especially if you don't have any tec mods installed (e.g grinder to grind cobble to sand). Sand can be really hard to come by if you don't have a desert nearby and it's such an important building material (glass) which is sometimes needed in huge masses.
Any specific reason you left this recipe out?

On top of my head I'd say one cobble(or gravel?) and the same amount of perditio required for wool->string would be a propper recipe.

**Comment by chrisbecke** [comment]
The specific reason this recipe was removed was because it causes problems. Cobblestone is frequently used as a source of perdito, as soon as this recipe is learnt it becomes impossible to use cobblestone to contribute perdito to a mix as every other piece absorbs the previous pieces perdito and becomes sand.

That said, the ability to make sand was a godsend. As it is, in my current server world, the closest desert if 4km from spawn, and I would relish, instead of the long trip, the prospect of dealing with the inevitable flux fallout from mass producing sand.

I hope Azanor comes up with some improvement on alchemy - as it stands there is an issue with using gunpowder in recipes as a source of essentia as gunpowder contains its own duplication recipe as aspects.

**Comment by ReTeYeZ** [comment]
Indeed that is a problem. My second thought as mentiod above would be gravel + perditio though gravel is relatively rair (for a building material). A recipe for gravel like dirt + perditio would help though it might make it to easy to get flint (but it's not very valuable anyway).

Another idea I have is:
Aqua + Dirt = Sand
In my head this makes sense and it adds a little bit more variation to the alchemy recipes (not perditio everywhere).
