### ISSUE TITLE
Seal GUI is bugged :|

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#464]
doesn't display any content, but "button.category.-1" at the top
Edit: in combination with OpenComputers-MC1.8.9-1.5.22.6

**Comment by Azanor** [comment]
All of them, or just one specific seal type?

**Comment by MalkContent** [comment]
as far as i can see, all of them

**Comment by Azanor** [comment]
Nope, works fine for me. Maybe remove and replace them?

**Comment by MalkContent** [comment]
Made a new world for this to check before reporting. I'll kick other mods, gimme a sec.

**Comment by MalkContent** [comment]
Okay. Happens with forge x1764, TC 5.2.0, OpenComputers-MC1.8.9-1.5.22.6

**Comment by MalkContent** [comment]
Log output when bell-clicking the seal:
http://pastebin.com/t7abqWBR

**Comment by Xiaminou** [comment]
confirmed.

![2016-03-04_16 40 14](https://cloud.githubusercontent.com/assets/8670392/13531638/e4c7e5f4-e227-11e5-9daa-8c21be3031be.png)
Log: http://pastebin.com/evfLjABP

**Comment by MalkContent** [comment]
also an issue with opencomputers for you, or a different mod?

**Comment by Xiaminou** [comment]
I haven't tested it further, but I do have opencomputers installed.

**Comment by Azanor** [comment]
I updated my dev environment to forge 1764 and everything still works fine for me, so I supsect  OC (or something else) might be the culprit. Its been in beta on two different mp servers (including FC1) and no one has reported this issue to me yet. I will take a look at the error in the log - it might be something I can catch on my end even if it isn't caused by TC.

**Comment by MalkContent** [comment]
The weird thing is, this wasn't an issue with the last version of tc, and the same version of oc.
Maybe coremods colliding or something, idk. I'll reference it to oc.

**Comment by Azanor** [comment]
The seal GUI has a custom version of the MC itemrenderer to the ghost slots in the filter. It is crashing in there while trying to register a item that seems to be null for some reason. I guess OC adds an item in there?

But yes, it is strange since I have not altered any of that code for 5.2 at all. Its been like that since seals were added.

**Comment by Azanor** [comment]
Ok, I have a workaround from my side. It is fairly obviously not a bug with either TC or OC. I think we are just both trying to fiddle with the same class which it does not like. I now fiddle a bit more gently on my side and it seems to have resolved the issue :p

**Comment by MalkContent** [comment]
all hail the mighty pistol squid <3 ^^
