### ISSUE TITLE
Arcing splash attack not influenced by enchantments

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#470]
-the arcing attack does not increase in damage from sharpness/smite/BoA enchants (yes, I am aware of the 0.5 multiplier), even though code suggests that it should
-doesn't set them on fire with fire aspect
-ignores knockback enchant and applies hardcoded knockback on par with ~knockback 1 enchant

upside:
-looting seems to work. i think.
-essentia harvester works definitly :)

chances are everything works as intended, but especially the first point seems worth the mention

**Comment by Azanor** [comment]
Well, none of those should apply since it isn't the weapon hitting the secondary targets, but a conjured gust of sharp wind.
Looting works as a side effect of the player holding a looting weapon while causing damage to something. It will be hard to prevent it actually, but I'm fine with it working like that. Ditto for essentia harvester.

**Comment by MalkContent** [comment]
could you rewrite it in the thaumonomicon to "for half your weapon's _base_ damage" to clear it up?
