### ISSUE TITLE
Grappler grappling point often not at blocksurface

### ISSUE THREAD

**Issue by MalkContent** [Azanor/thaumcraft-5#524]
The point the Grappler grapples onto often is way in front of the place where you would it expect to "impact" (talking multiple blocks distance).
Also at short distances the grappler does not work. This might well be related to the first issue, but I'm not 100% on that.
Maybe it's a sync issue.
Generally not much of an issue, but when you want to be very specific about where you want to grapple to, you might not be able to do it.

**Comment by Azanor** [comment]
It is a sync issue of sorts - entities are seldom in 100% the same place on the client and the server. For most things this is fine, but the speed of the grappler makes it more apparent especially if your ping to the server is not that bad. Impacts are calculated on the server side for the grappler so where it connects visually might not actually be where it is actually connected.
I'll try and fiddle with it a bit, but I doubt I can fix it much without making it worse in other ways.

**Comment by Azanor** [comment]
Easier to solve than I thought. Turns out projectiles have a built in inaccuracy rating even if you set their inaccuracy to 0. I just needed override that built in number. I also 'loosened' the syncing a bit. This means that the grapple will always be in the position where it actually impacted a block, but that occasionally it might change position slightly once the client catches up to the server - this should have very little if any influence on the actual pull.
