### ISSUE TITLE
Tainted Lands are not generating regardless of config option

### ISSUE THREAD

**Issue by minpav** [Azanor/thaumcraft-5#561]
The Tainted Lands biome does not generate in the world. I have the config option set to true.
(I have tried versions 5.2.1 and 5.2.4)

**Comment by codewarrior0** [comment]
I haven't found any yet in newer versions, but I remember in 5.1.3 tainted lands are either incredibly rare, or only ever generated around Tainted nodes. I've always resorted to dumping a chest of logs into a crucible to create my own tainted land.

**Comment by minpav** [comment]
I've searched a large area with journy map mod, but the only taint biome I've found is around two tainted nodes (and both have just few blocks).
In Thaumcraft 4 Tainted Lands weren't so rare so I decided to decompile thaumcraft and search for the tainted biome in code. And it seems **it's not** even **registered for generation**, while Magic Forest is registered two times (as a cold and as a warm biome)

**Comment by Hyxaru** [comment]
Tainted lands biomes as natural generation have been removed ever since thaumcraft 5. All taint found is found in the following ways:
-player induced flux pollution through machines and aura exhaustion
-Tainted nodes, and hungry nodes indirectly through aura exhaustion, can be found everywhere but are rare
-Performing the Oculus Apertis creates flux 'on the other side', as well as that taint can be found there in some parts
-Infested champion mobs can spawn tainted crawlers upon getting hit. They spawn fibrious taint under them, though they will quickly die if there was no flux in the aura already to support taint growth.
-The warp effect causing thaumaria will create flux goo under the player, which will dissipate into flux over some time.

**Comment by jochuan** [comment]
if your question was answered you should close this
