### ISSUE TITLE
Bungee

### ISSUE THREAD

**Issue by Wolf1098** [Azanor/thaumcraft-5#573]
Would it be possible to make thaumcraft work with bungee, Currently you have to use a server's direct ip or some thaumcraft items refuse to work

**Comment by thomas15v** [comment]
Took me a while to figure out this issue. But the problem isn't bungeecord nor thaumcraft. The problem lies in the minecraft protocol and the challenge bungeecord brings.

When a player join a server on bungeecord, it gets asigned a entity id on that specific server. However when the client switches to another server the client id on the new server will be different. Bungee itself counteracts this problem by rewriting all know packets and changing their id's.

However thaumcraft is one of those mods that uses the entity id of the player for some of it's packets. What causes everything to go haywire when a player switches servers. As a proof of concept I also fixed the problem in the form of a bungeecord plugin: https://github.com/densitycraft/ForgePacketFix

**Comment by Azanor** [comment]
Hmmm, I'll look into this. Maybe there is a light-weight alternative to me sending the id.

**Comment by thomas15v** [comment]
I would recommend using the playername like thaumcraft does with some packets. It's only a string of 16 characters and is unique on any online server (unless the username gets saved somewhere).
